language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/Mybackend.jar -t $DOCKER_USERNAME/se234-lab10-backend
  .
- docker push kuribohw/se234-lab10-backend
- docker pull kuribohw/se234-lab10-client
script:
- docker-compose -H "$HOST_NAME" stop
- docker-compose -H "$HOST_NAME" rm -f
- docker-compose -H "$HOST_NAME" pull
- docker-compose -H "$HOST_NAME" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: wieHYSodl94r3xo0TvBJjVxEoMH6lr6Pgn5TSpskw4unOqwYqThwuVd+B+YLxd8KKi9ZRsij4AqLg/d8w9J+sxKM6iiPf2bmfw5HyEMLLydNiXfOp/FtkeWAozD+o3Q7lZkCHvbAinTJHjAKK04UYsk/yH0KN9zBT184ThgRJgKyyOyo8ru9axQm0xtseR6eeXuAF4erIY/rBUelK3dQMCSCZZxtDnX/yrIaBySaOXF0LqSLwb8u/sO98OBmQFZxkdPq0wkPpd4Fa6iP7ZSTlekdU6mpnO/h5fbJjffilixqZ2UqiisKiVB64qrZXRQX8Erdco93AgtvTratanmiKrB6PJQBO1uXam7KReS7KbIl3oCW5z6N+OkyIYjvoDQ4lIbmhxjPLqtilAqFRT2i+EAee/6GICO5C8Jmq+sckZGS1CM+0JLxxqdN2RiBPj9QZkzxbgfQsK9VQ8P9w58Fy+NXTULvsxTGQXD6hDKRLNrYO/QvDqNEA0fvk1bcr6voEHX1wuy5rKg0mmsAQZkdxpxAH5sX6pQr+EXGjnF5lb5QLYPX8Ydyk3v16prStimyuC0nEKHEdtLxoN+vZ7+kHemcGdsaEvsYBbmtbWxPWpSPII8QCKRkyyw7HwCjyp90GecIVoiOf529ODd0WxtDHGI01LM6gBZUlC1aN3olfXQ=
  - secure: sws6P4Suf2qLOm+vPs+OtN/qe1KCZmSVHx47bLt4bcigiYJtgIrAap91XZYsC810SD4dP2VNA44uOng5sYVbobHtgKFyFHJLNkhpULx8LcQ2XwgldbHN22lid8ZeCvsEacHoPvyZ+/P7MaJxQlivcv/+Pi8FGeBmdT7LaOpmEoXQS6O0PfTx17lAyUOml3rpAW9UaDNBvEcN+4zncMWHsbCqoBh+x4nJZdTT+ArPp4lTNkDRACRU7VQeASFxqIGflmxY0TZjWe+xtCvaAyH54XB1voTL8BxcMAkHKUNU3sZjieCzK8Z9sbdaE23S+mXLYhtbQQPLfPMi0IcB4TJGau8mYh/HJNsF6vD1JLkMLDL+ZyM4MWUZTju6qYX6ud40RS5cIW/rPSrk48IhyZJ+vBPcesY8WgYuvIWTWDWs3g37eidAF6eKBkM39FtnosjYwMGy2AwHUcqaKg1eYMIz61LNRAq3i1SLXAODVwGn2BNsYB90PAbZ29UCkmDxHxJ7tGYf3ZCH+UpUT2+vQYP53sNUlIKnGAbgW5eJjNWMxd3+JEeTcbml6drMBaaPhdCM/f5pHAFZ/FOQK68Q0y0cH6NRFB2xpHNcO+UttNHIglrHF+sMMaw1PgWuoN/Rltrfpzbo4ZDGnOt26Sxpz3GPKhwwl7nylgOP59wnVj73Q+U=
  - secure: LDOQf8vD1b5n8+0LPpgq0jsgs+dwjveAG8bQ1bN4FHV6kHL96n/yfrd8B8+w//Bjp5NDYsqMe1ro6ztijVPKfgwTrFGtTMxG3sXKEJCxfKQTq02PbyooLY1O2uOeBFmfgS1S09aYjJZGOXSgYlx8uqofGbAK8kdd/xzqotxW5X1fJhVlMYuQpxwK1jGW0u1xvsBr5izP0TUiGPFpoxAN0Ixh5YS7i48SiALibrRQMwa5AsqvrOkK5QNfm9ChRfu3LpyKvWPICNUQK6eCQuoorPX2xrXBGc3RtePcudKlzHYWOzchKVCTryyEEO+lPkj2WsUEqKonaMlUve4WMkcnXGdOnX1rr6DT+vSaSk9lfB7ttCLn/VGpQlvZN8/59arg1KNagObzZ43rX+OsADAY+jdLy7jRohtc/TsHa4F0Q7nuQf2gMt8QmuI3pMq4E/BfOpwlh+pfq9VcNtyfwC0nZElGiS99PRIgFPDVBg7nw3OFWgtIAwC+JWUFwrU1J/1cmFcfgApSz1iwxQDmXBADXPNLckA8ED+mUliOa7++xjh72hSAlW5M7lE0oSXN7lbW8ZV0RGn0M7Nk1/Lcij8iuNzUjfbLSrP5Ys8foSsXHQcnMjBz012xRWdgm+TAcMK6m0Izm94wtA7ob/iiS6GS7zKamGGkBcFEHoy/evVPQBE=
